"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Tensor(_message.Message):
    """===== 通用张量结构 ====="""

    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    SHAPE_FIELD_NUMBER: _builtins.int
    DTYPE_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    """numpy.tobytes() 序列化后的原始字节"""
    dtype: _builtins.str
    """数据类型，如 "float32", "uint8", "int64" """
    @_builtins.property
    def shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """张量维度，例如 [84, 84, 3]"""

    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        shape: _abc.Iterable[_builtins.int] | None = ...,
        dtype: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "dtype", b"dtype", "shape", b"shape"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Tensor: _TypeAlias = Tensor  # noqa: Y015

@_typing.final
class TensorList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___Tensor]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[Global___Tensor] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TensorList: _TypeAlias = TensorList  # noqa: Y015

@_typing.final
class TensorDict(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FieldsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___Tensor: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___Tensor | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    FIELDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def fields(self) -> _containers.MessageMap[_builtins.str, Global___Tensor]: ...
    def __init__(
        self,
        *,
        fields: _abc.Mapping[_builtins.str, Global___Tensor] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fields", b"fields"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TensorDict: _TypeAlias = TensorDict  # noqa: Y015

@_typing.final
class TensorValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TENSOR_FIELD_NUMBER: _builtins.int
    LIST_FIELD_NUMBER: _builtins.int
    DICT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tensor(self) -> Global___Tensor: ...
    @_builtins.property
    def list(self) -> Global___TensorList: ...
    @_builtins.property
    def dict(self) -> Global___TensorDict: ...
    def __init__(
        self,
        *,
        tensor: Global___Tensor | None = ...,
        list: Global___TensorList | None = ...,
        dict: Global___TensorDict | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dict", b"dict", "kind", b"kind", "list", b"list", "tensor", b"tensor"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dict", b"dict", "kind", b"kind", "list", b"list", "tensor", b"tensor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["tensor", "list", "dict"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___TensorValue: _TypeAlias = TensorValue  # noqa: Y015

@_typing.final
class EnvRequest(_message.Message):
    """===== 客户端请求 ====="""

    DESCRIPTOR: _descriptor.Descriptor

    RESET_FIELD_NUMBER: _builtins.int
    STEP_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def reset(self) -> Global___Reset: ...
    @_builtins.property
    def step(self) -> Global___Step: ...
    @_builtins.property
    def close(self) -> Global___Close: ...
    def __init__(
        self,
        *,
        reset: Global___Reset | None = ...,
        step: Global___Step | None = ...,
        close: Global___Close | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "cmd", b"cmd", "reset", b"reset", "step", b"step"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "cmd", b"cmd", "reset", b"reset", "step", b"step"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_cmd: _TypeAlias = _typing.Literal["reset", "step", "close"]  # noqa: Y015
    _WhichOneofArgType_cmd: _TypeAlias = _typing.Literal["cmd", b"cmd"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_cmd) -> _WhichOneofReturnType_cmd | None: ...

Global___EnvRequest: _TypeAlias = EnvRequest  # noqa: Y015

@_typing.final
class EnvReply(_message.Message):
    """===== 服务端回复 ====="""

    DESCRIPTOR: _descriptor.Descriptor

    RESET_FIELD_NUMBER: _builtins.int
    STEP_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def reset(self) -> Global___ResetReply: ...
    @_builtins.property
    def step(self) -> Global___StepReply: ...
    @_builtins.property
    def close(self) -> Global___CloseReply: ...
    def __init__(
        self,
        *,
        reset: Global___ResetReply | None = ...,
        step: Global___StepReply | None = ...,
        close: Global___CloseReply | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "reset", b"reset", "result", b"result", "step", b"step"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "reset", b"reset", "result", b"result", "step", b"step"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["reset", "step", "close"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___EnvReply: _TypeAlias = EnvReply  # noqa: Y015

@_typing.final
class Reset(_message.Message):
    """===== Reset ====="""

    DESCRIPTOR: _descriptor.Descriptor

    SEED_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def seed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def options(self) -> _containers.RepeatedCompositeFieldContainer[_struct_pb2.Struct]: ...
    def __init__(
        self,
        *,
        seed: _abc.Iterable[_builtins.int] | None = ...,
        options: _abc.Iterable[_struct_pb2.Struct] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["options", b"options", "seed", b"seed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Reset: _TypeAlias = Reset  # noqa: Y015

@_typing.final
class ResetReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBSERVATION_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def observation(self) -> Global___TensorValue: ...
    @_builtins.property
    def info(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        observation: Global___TensorValue | None = ...,
        info: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["info", b"info", "observation", b"observation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["info", b"info", "observation", b"observation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResetReply: _TypeAlias = ResetReply  # noqa: Y015

@_typing.final
class Step(_message.Message):
    """===== Step ====="""

    DESCRIPTOR: _descriptor.Descriptor

    ACTION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def action(self) -> Global___TensorValue: ...
    def __init__(
        self,
        *,
        action: Global___TensorValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Step: _TypeAlias = Step  # noqa: Y015

@_typing.final
class StepReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBSERVATION_FIELD_NUMBER: _builtins.int
    REWARD_FIELD_NUMBER: _builtins.int
    TERMINATED_FIELD_NUMBER: _builtins.int
    TRUNCATED_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def observation(self) -> Global___TensorValue: ...
    @_builtins.property
    def reward(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def terminated(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bool]: ...
    @_builtins.property
    def truncated(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bool]: ...
    @_builtins.property
    def info(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        observation: Global___TensorValue | None = ...,
        reward: _abc.Iterable[_builtins.float] | None = ...,
        terminated: _abc.Iterable[_builtins.bool] | None = ...,
        truncated: _abc.Iterable[_builtins.bool] | None = ...,
        info: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["info", b"info", "observation", b"observation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["info", b"info", "observation", b"observation", "reward", b"reward", "terminated", b"terminated", "truncated", b"truncated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StepReply: _TypeAlias = StepReply  # noqa: Y015

@_typing.final
class Close(_message.Message):
    """===== Close ====="""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Close: _TypeAlias = Close  # noqa: Y015

@_typing.final
class CloseReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CloseReply: _TypeAlias = CloseReply  # noqa: Y015
