# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lockon.protos.gym_v2 import gym_env_pb2 as lockon_dot_protos_dot_gym__v2_dot_gym__env__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lockon/protos/gym_v2/gym_env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GymEnvStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEnv = channel.stream_stream(
                '/gym_v2.GymEnv/StreamEnv',
                request_serializer=lockon_dot_protos_dot_gym__v2_dot_gym__env__pb2.EnvRequest.SerializeToString,
                response_deserializer=lockon_dot_protos_dot_gym__v2_dot_gym__env__pb2.EnvReply.FromString,
                _registered_method=True)


class GymEnvServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamEnv(self, request_iterator, context):
        """单一的双向流，客户端发命令，服务端回结果。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GymEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEnv': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEnv,
                    request_deserializer=lockon_dot_protos_dot_gym__v2_dot_gym__env__pb2.EnvRequest.FromString,
                    response_serializer=lockon_dot_protos_dot_gym__v2_dot_gym__env__pb2.EnvReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gym_v2.GymEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gym_v2.GymEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GymEnv(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamEnv(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gym_v2.GymEnv/StreamEnv',
            lockon_dot_protos_dot_gym__v2_dot_gym__env__pb2.EnvRequest.SerializeToString,
            lockon_dot_protos_dot_gym__v2_dot_gym__env__pb2.EnvReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
